// <auto-generated />
namespace Over9000.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class abcdefg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcdefg));
        
        string IMigrationMetadata.Id
        {
            get { return "202004292031102_abcdefg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
